### ISSUE TITLE
Parallelize the time axis in the GCR step

### ISSUE THREAD

**Issue by jburba** [HydraRadio/hydra-pspec#11]
Replace the `multiprocess.Pool` call on [line 223](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/hydra_pspec/pspec.py#L223) in [hydra_pspec.pspec.gcr_fgmodes](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/hydra_pspec/pspec.py#L175) with MPI functionality.

Background
----------
As Phil mentioned on our initial call, we have three axes in our data that we are concerned with:
1. Baseline (a pair of antennas in an interferometer forms a baseline)
2. Time (the axis we want to parallelize)
3. Frequency

The function [gcr_fgmodes](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/hydra_pspec/pspec.py#L175) gets passed data with shape `(Ntimes, Nfreqs)` where `Ntimes` is the number of times and `Nfreqs` is the number of frequencies.  Each time is handled independently in [gcr_fgmodes_1d](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/hydra_pspec/pspec.py#L88) which is passed a subset of the data with shape `(Nfreqs,)`, i.e. a single spectrum.  We currently use `multiprocess.Pool` to call `gcr_fgmodes_1d` from within `gcr_fgmodes` and want to replace that `multiprocess` call with an MPI call.

Notes
-----
- We found only recently that `multiprocess.Pool` shares the random seed of the parent with all child tasks which was introducing unwanted, [spurious correlations](https://github.com/HydraRadio/hydra-pspec/issues/7) between times in our model.  We are currently using the process ID and time index to generate a unique, deterministic, random seed for each process/worker in [gcr_fgmodes_1d (line 132)](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/hydra_pspec/pspec.py#L132).  I don't know if random seeds are shared across MPI processes, but **it's important that each process gets a unique, deterministic, random seed**.

ToDos
-----
- [x] @jburba will add some test data to the hydra-pspec repo and provide a conda environment yaml file and a README for running the code using the test data (added in [799b182](https://github.com/HydraRadio/hydra-pspec/commit/799b182d57754628a23330aa6ab773fb2b4442fe))
- [x] @jburba will remove the MPI calls in the driver script `hydra-pspec/run-hydra-pspec.py` so we can instead parallelize over the time axis (see #12 )

**Comment by ianhinder** [comment]
@gcapes did you get a small example which can be run quickly?

Should this issue be closed, since we have now decided to parallelise over baseline rather than time?

**Comment by gcapes** [comment]
I've reduced the number of iterations to reduce the run time, so yes.
I'm not sure how to do anything about the warning though.

**Comment by jburba** [comment]
@gcapes you can ignore the warning.  The input data is simulated from a fake telescope.  The package throwing the warning (pyuvdata) has some metadata for known telescopes (antenna sizes, locations, etc).  It doesn't know about the fake telescope I've created, that's what the warning is saying.  It will happen every time the simulated data is read in with pyuvdata.

**Comment by jburba** [comment]
I think it's okay to close this issue since it's not possible to parallelize over the time axis in the way this issue initially suggested.  For parallelizing over the baseline axis, you could have a look at a previous commit ([cbf1c42](https://github.com/HydraRadio/hydra-pspec/commit/cbf1c425501fd12a1d268e26832ea93e8d0c5769)) where I implemented a rudimentary MPI baseline parallelization.  The baseline parallelization is in the driver script on that commit, [run-hydra-pspec.py](https://github.com/HydraRadio/hydra-pspec/blob/a73bbea0401673a4d233b77ccef1a386f88b0325/run-hydra-pspec.py).
